[package]
name = "render_gl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "*"
glm = "*"
nalgebra = "*"
nalgebra-glm = "*"
sdl2 = "0.35"
image = "0.24.5"
freetype = "0.7.0"