[package]
name = "render_gl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
nalgebra = "*"
nalgebra-glm = "*"
sdl2 = "0.35"
image = "0.24.5"
rusttype = "0.9.3"
freetype-rs = "0.34.0"